ocean_data:
  - name: nycodar_hfr
    data: data/codar_thing/NYCODAR_2021_2022_cruise1.nc
    allow_time_extrapolation: false
parcels_config:
  save_dir: results
  particle_type: pyplume.kernels.ThreddsParticle
  kernels:
    - parcels.AdvectionRK4
    - pyplume.kernels.RandomWalk5cm
    - pyplume.kernels.AgeParticle
    - pyplume.kernels.DeleteStatusOutOfBounds
  time_range: [2021-05-16T00:00, 2021-05-21T00:00]
  repeat_dt: 3600
  repetitions: -1
  instances_per_spawn: 1
  # spawn_points: data/codar_thing/StationPts.mat
  spawn_points:
    - label: release
      point: [39.71278333, -73.50068333]
      pattern:
        type: grid
        size: 5
        gapsize: 0.005
  simulation_dt: -1200
  snapshot_interval: 7200
postprocess_config: {}
plotting_config:
  plots:
    - type: pyplume.resultplots.ParticlePlot
      label: particleplots
      coastline: true
      draw_currents: false
      particle_color: lifetime
      domain:
        S: 39.3
        N: 40.4
        W: -74
        E: -73
      # addons:
      #   - type: pyplume.resultplots.AddScatter
      #     data: data/codar_thing/StationPts.mat
      #     color: r
      #     size: 20
    - type: pyplume.resultplots.CumulativeParticleDensityPlot
      domain:
        S: 39.3
        N: 40.4
        W: -74
        E: -73
      coastline: true

